on: [push, pull_request]

jobs:
  directories:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: marten-seemann/multiple-go-modules@master
      with:
        run: |
          pwd
          echo "command failed"
          exit 1
